#ifndef _DOWNLOAD_H_
#define _DOWNLOAD_H_

// |---------------------------------------------------------------|
// | A0 | Size | P1 | P2 | P3 |......| Pn | CheckSum | Size | 0xFF |
// |---------------------------------------------------------------|
#define DOWNLOAD_MODE_HEADER 		0xA0
#define DOWNLOAD_FEEDBACK_HEADER	0xB0
#define DOWNLOAD_MODE_END	 		0xFF
#define DOWNLOAD_MODE_MAX_PROTOCAL_SIZE 256   //Data Size+5(header,checksum,Size,size,end Value < VISCA_SW_BUF_SIZE
#define DOWNLOAD_MODE_PROTOCAL_SIZE 	256   //the value must <= DOWNLOAD_MODE_MAX_PROTOCAL_SIZE
#define DOWNLOAD_MODE_FEEDBACK_SIZE 3

//P1 value
#define DOWNLOAD_DATA_MODE_00 	0x01
#define DOWNLOAD_DATA_MODE_FF	0x02
#define DOWNLOAD_DATA_MODE_ALL 	0x03

#define CONTROL_CMD_PROTOCOL_NAK	0x7F

#define CONTROL_CMD_PROTOCOL_SIZE 	0x07
#define CONTROL_CMD_PROTOCOL_P1 	0x11
#define CONTROL_CMD_PROTOCOL_P2		0x22
#define CONTROL_CMD_PROTOCOL_P3		0x33
#define CONTROL_CMD_PROTOCOL_P4 	0x44

#define CONTROL_CMD_PROTOCOL_P5_TYPE		0x51
#define CONTROL_CMD_PROTOCOL_P5_CONTROL		0x52

#define CONTROL_CMD_PROTOCOL_TYPE_P6_FPGA 	0x01
#define CONTROL_CMD_PROTOCOL_TYPE_P6_MIPI 	0x02
#define CONTROL_CMD_PROTOCOL_TYPE_P6_ISP	0x03
#define CONTROL_CMD_PROTOCOL_TYPE_P6_MOTOR	0x04
#define CONTROL_CMD_PROTOCOL_TYPE_P6_MAIN	0x05

#define CONTROL_CMD_PROTOCOL_ERROR		0x00
#define CONTROL_CMD_PROTOCOL_TYPE		0x01
#define CONTROL_CMD_PROTOCOL_CONTROL	0x02
#define CONTROL_CMD_PROTOCOL_DATA		0x03
#define CONTROL_CMD_PROTOCOL_INQUERY	0x04

//CONTROL_CMD_PROTOCOL_CONTROL command
#define CONTROL_CMD_PROTOCOL_CONTROL_P6_UART_BYPASS 0x00
#define CONTROL_CMD_PROTOCOL_CONTROL_P6_CHIP_ERASE 0x01
#define CONTROL_CMD_PROTOCOL_CONTROL_P6_INIT 0x02
#define CONTROL_CMD_PROTOCOL_CONTROL_P6_START_ADDR 0x03
#define CONTROL_CMD_PROTOCOL_CONTROL_P6_CHECKSUM 0x04
#endif

